package com.scl.plugin.wizard

import com.intellij.ide.util.projectWizard.WizardContext
import com.intellij.ide.wizard.AbstractNewProjectWizardStep
import com.intellij.ide.wizard.GeneratorNewProjectWizard
import com.intellij.ide.wizard.NewProjectWizardBaseStep
import com.intellij.ide.wizard.NewProjectWizardStep
import com.intellij.openapi.observable.properties.PropertyGraph
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.UserDataHolderBase
import com.intellij.ui.dsl.builder.Panel
import com.scl.plugin.SclIcons
import java.io.File
import javax.swing.Icon

class SclNewProjectWizard : GeneratorNewProjectWizard {
    override val id   = "SCL"
    override val name = "SCL"
    override val icon: Icon = SclIcons.FUNCTION_BLOCK

    override fun createStep(context: WizardContext): NewProjectWizardStep {
        val root = object : NewProjectWizardStep {
            override val context       = context
            override val data          = UserDataHolderBase()
            override val propertyGraph = PropertyGraph()
            override val keywords      = NewProjectWizardStep.Keywords()
            override fun setupUI(builder: Panel) {}
            override fun setupProject(project: Project) {}
        }
        val base = NewProjectWizardBaseStep(root)
        return SclNewProjectWizardStep(base)
    }
}

private class SclNewProjectWizardStep(
    private val base: NewProjectWizardBaseStep
) : AbstractNewProjectWizardStep(base) {

    override fun setupUI(builder: Panel) {}

    override fun setupProject(project: Project) {
        // Propagate up so NewProjectWizardBaseStep commits name/path into WizardContext
        base.setupProject(project)

        val dir = project.basePath ?: return
        File(dir).mkdirs()

        File(dir, "FB_Main.scl").writeText(
            """
            FUNCTION_BLOCK "FB_Main"
            { S7_Optimized_Access := 'TRUE' }
            //=============================================================
            // FB_Main — Generated by SCL Language Support plugin
            //=============================================================

            VAR_INPUT
                i_Enable  : Bool;   // Enable signal
            END_VAR

            VAR_OUTPUT
                o_Running : Bool;   // Running status
            END_VAR

            VAR
                s_State : Int := 0;
            END_VAR

            BEGIN
                IF i_Enable THEN
                    o_Running := TRUE;
                    s_State   := 1;
                ELSE
                    o_Running := FALSE;
                    s_State   := 0;
                END_IF;
            END_FUNCTION_BLOCK
            """.trimIndent()
        )
    }
}
